server:
  port: 8081
  servlet.context-path : /xc_hello


myapollo:
  cluster: @activatedProfile@
  env: @apollo.env@

apollo:
  bootstrap:
    enabled: true
    namespaces:


spring:
  data:
    elasticsearch:
      cluster-name: myapplication
      cluster-nodes: 127.0.0.1:9300
  application:
    name: xchello #此处需唯一，取上线计划wiki的名称
  cloud:
    consul:
      discovery:
        health-check-critical-timeout: 30m #服务下线到从UI界面消失的时间间隔
        health-check-interval: 1s #健康检查时间间隔
        health-check-path: ${server.servlet.context-path}/info #健康检查的接口地址，即现在项目中对healthcheck.html检查的接口地址
        health-check-timeout: 1s    #健康检查超时时间
        instance-id: ${spring.application.properties.name}-127.0.0.1-${server.port}   #注册到注册中心的服务ID
        prefer-ip-address: true  #使用IP注册
         #query-passing: true              #只查询健康的服务列表
      host: 127.0.0.1
      port: 8501












